<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class EquipmentTableSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('equipment')->insert(
            [
                [
                    'equipment_id' => 1,
                    'equipment_number' => '5-7110-1-38-61-220',
                    'equipment_name' => 'เก้าอี้ฟังคำบรรยาย แบบ n.03 พื้นรองนั่งเขียนทำด้วยไม้อัด ส่วนกว้างที่สุด 38 ซม. แคบที่สุด 9.5 ซม. หนา 2 ซม.',
                    'equipment_unit_price' => 585.00,
                    'description' => 'โอนไปเครื่องกล',
                    'user_id' => null,
                    'location_of_equipment' => 'เครื่องกล',
                    'equipment_unit' => 'ตัว',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'deleted_at' => null,
                    'created_by' => null,
                    'updated_by' => null,
                    'deleted_by' => null
                ],
                [
                    'equipment_id' => 2,
                    'equipment_number' => '2355-2234-060-02-1(8)',
                    'equipment_name' => 'เครื่องคอมพิวเตอร์แม่ข่าย ยี่ห้อ IBM รุ่น x250 รับบริจาคจากบริษัทโตโยต้าลิสซิ่ง (ประเทศไทย)จำกัด',
                    'equipment_unit_price' => null,
                    'description' => '- ห้อง server (วศ.1061) -อท505 1 ตัว',
                    'user_id' => null,
                    'location_of_equipment' => 'ห้อง server วศ.1061',
                    'equipment_unit' => 'เครื่อง',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'deleted_at' => null,
                    'created_by' => null,
                    'updated_by' => null,
                    'deleted_by' => null
                ],
                [
                    'equipment_id' => 3,
                    'equipment_number' => '2355-2234-060-02-2(8)',
                    'equipment_name' => 'เครื่องคอมพิวเตอร์แม่ข่าย ยี่ห้อ IBM รุ่น x250 รับบริจาคจากบริษัทโตโยต้าลิสซิ่ง (ประเทศไทย)จำกัด',
                    'equipment_unit_price' => null,
                    'description' => '',
                    'user_id' => null,
                    'location_of_equipment' => 'ห้อง server วศ.1061',
                    'equipment_unit' => 'เครื่อง',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'deleted_at' => null,
                    'created_by' => null,
                    'updated_by' => null,
                    'deleted_by' => null
                ],
                [
                    'equipment_id' => 4,
                    'equipment_number' => '2355-2234-060-02-3(8)',
                    'equipment_name' => 'เครื่องคอมพิวเตอร์แม่ข่าย ยี่ห้อ IBM รุ่น x250 รับบริจาคจากบริษัทโตโยต้าลิสซิ่ง (ประเทศไทย)จำกัด',
                    'equipment_unit_price' => null,
                    'description' => '',
                    'user_id' => null,
                    'location_of_equipment' => 'ห้อง server วศ.1061',
                    'equipment_unit' => 'เครื่อง',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'deleted_at' => null,
                    'created_by' => null,
                    'updated_by' => null,
                    'deleted_by' => null
                ],
                [
                    'equipment_id' => 5,
                    'equipment_number' => '2355-2234-060-02-4(8)',
                    'equipment_name' => 'เครื่องคอมพิวเตอร์แม่ข่าย ยี่ห้อ IBM รุ่น x250 รับบริจาคจากบริษัทโตโยต้าลิสซิ่ง (ประเทศไทย)จำกัด',
                    'equipment_unit_price' => null,
                    'description' => '',
                    'user_id' => null,
                    'location_of_equipment' => 'ห้อง server วศ.1061',
                    'equipment_unit' => 'เครื่อง',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'deleted_at' => null,
                    'created_by' => null,
                    'updated_by' => null,
                    'deleted_by' => null
                ],
                [
                    'equipment_id' => 6,
                    'equipment_number' => '2355-2234-060-02-5(8)',
                    'equipment_name' => 'เครื่องคอมพิวเตอร์แม่ข่าย ยี่ห้อ IBM รุ่น x250 รับบริจาคจากบริษัทโตโยต้าลิสซิ่ง (ประเทศไทย)จำกัด',
                    'equipment_unit_price' => null,
                    'description' => '',
                    'user_id' => null,
                    'location_of_equipment' => 'ห้อง server วศ.1061',
                    'equipment_unit' => 'เครื่อง',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'deleted_at' => null,
                    'created_by' => null,
                    'updated_by' => null,
                    'deleted_by' => null
                ],
                [
                    'equipment_id' => 7,
                    'equipment_number' => '2355-2234-060-02-6(8)',
                    'equipment_name' => 'เครื่องคอมพิวเตอร์แม่ข่าย ยี่ห้อ IBM รุ่น x250 รับบริจาคจากบริษัทโตโยต้าลิสซิ่ง (ประเทศไทย)จำกัด',
                    'equipment_unit_price' => null,
                    'description' => '',
                    'user_id' => null,
                    'location_of_equipment' => 'ห้อง server วศ.1061',
                    'equipment_unit' => 'เครื่อง',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'deleted_at' => null,
                    'created_by' => null,
                    'updated_by' => null,
                    'deleted_by' => null
                ],
                [
                    'equipment_id' => 8,
                    'equipment_number' => '2355-2234-060-02-7(8)',
                    'equipment_name' => 'เครื่องคอมพิวเตอร์แม่ข่าย ยี่ห้อ IBM รุ่น x250 รับบริจาคจากบริษัทโตโยต้าลิสซิ่ง (ประเทศไทย)จำกัด',
                    'equipment_unit_price' => null,
                    'description' => '',
                    'user_id' => null,
                    'location_of_equipment' => 'ห้อง server วศ.1061',
                    'equipment_unit' => 'เครื่อง',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'deleted_at' => null,
                    'created_by' => null,
                    'updated_by' => null,
                    'deleted_by' => null
                ],
                [
                    'equipment_id' => 9,
                    'equipment_number' => '2355-2234-060-02-8(8)',
                    'equipment_name' => 'เครื่องคอมพิวเตอร์แม่ข่าย ยี่ห้อ IBM รุ่น x250 รับบริจาคจากบริษัทโตโยต้าลิสซิ่ง (ประเทศไทย)จำกัด',
                    'equipment_unit_price' => null,
                    'description' => '',
                    'user_id' => null,
                    'location_of_equipment' => 'อท 505',
                    'equipment_unit' => 'เครื่อง',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'deleted_at' => null,
                    'created_by' => null,
                    'updated_by' => null,
                    'deleted_by' => null
                ],
                [
                    'equipment_id' => 10,
                    'equipment_number' => '2355-2234-060-187-1(1)',
                    'equipment_name' => 'Storage ยี่ห้อ IBM Fast 4300 รับบริจาคจากบริษัทโตโยต้าลิสซิ่ง (ประเทศไทย)จำกัด',
                    'equipment_unit_price' => null,
                    'description' => '',
                    'user_id' => null,
                    'location_of_equipment' => 'ห้อง server วศ.1061',
                    'equipment_unit' => 'เครื่อง',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'deleted_at' => null,
                    'created_by' => null,
                    'updated_by' => null,
                    'deleted_by' => null
                ],
                [
                    'equipment_id' => 11,
                    'equipment_number' => '2255-2234-060-10-1(3)',
                    'equipment_name' => 'เครื่องคอมพิวเตอร์เพื่อการออกแบบยี้ห้อ acer รุ่น Veriton M4610G s/n.11188268 CPU เป็นแบบ 2 nd generation Intel Core i3-2120 Ram 2 GB เป็นแบบ DDR3RAM 1066/1333 MHz Hard disk SATA II ขนาด 500 GB Power Supply ขนาด 300 วัตต์ เมาส์ Optical Scroll แบบ USB พร้อมแผ่นรองเมาส์ จอภาพสีชนิด TFTLCD ขนาด 18.5 นิ้ว ความละเอียด 1366x768 จุด',
                    'equipment_unit_price' => 19900.00,
                    'description' => 'อ.นิพนธ์',
                    'user_id' => 2,
                    'location_of_equipment' => 'จ.2/4/55',
                    'equipment_unit' => null,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'deleted_at' => null,
                    'created_by' => null,
                    'updated_by' => null,
                    'deleted_by' => null
                ],
                [
                    'equipment_id' => 12,
                    'equipment_number' => '2255-2234-060-10-1(3)/1-1(1)',
                    'equipment_name' => 'โต๊ะคอมพิวเตอร์ 1 ตัว บนาด 80x60x75 ซม.มีชั้นวางเคสด้านล่าง ชั้นวางแป้นพิมพ์ มีรูร้อยสายด้านบนและด้านหลัง',
                    'equipment_unit_price' => null,
                    'description' => 'จำหน่ายแล้ว 2561',
                    'user_id' => null,
                    'location_of_equipment' => null,
                    'equipment_unit' => 'ตัว',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'deleted_at' => null,
                    'created_by' => null,
                    'updated_by' => null,
                    'deleted_by' => null
                ],
                [
                    'equipment_id' => 13,
                    'equipment_number' => '2255-2234-060-10-1(3)/1-2(2)',
                    'equipment_name' => 'โต๊ะคอมพิวเตอร์ 1 ตัว บนาด 80x60x75 ซม.มีชั้นวางเคสด้านล่าง ชั้นวางแป้นพิมพ์ มีรูร้อยสายด้านบนและด้านหลัง',
                    'equipment_unit_price' => null,
                    'description' => 'ห้องปฏิบัติการ',
                    'user_id' => null,
                    'location_of_equipment' => null,
                    'equipment_unit' => 'ตัว',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'deleted_at' => null,
                    'created_by' => null,
                    'updated_by' => null,
                    'deleted_by' => null
                ],
                [
                    'equipment_id' => 14,
                    'equipment_number' => '2255-2234-060-10-1(3)/2-1(3)',
                    'equipment_name' => 'โต๊ะคอมพิวเตอร์ 1 ตัว บนาด 80x60x75 ซม.มีชั้นวางเคสด้านล่าง ชั้นวางแป้นพิมพ์ มีรูร้อยสายด้านบนและด้านหลัง',
                    'equipment_unit_price' => null,
                    'description' => 'โอนให้ จป.',
                    'user_id' => null,
                    'location_of_equipment' => null,
                    'equipment_unit' => 'ตัว',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'deleted_at' => null,
                    'created_by' => null,
                    'updated_by' => null,
                    'deleted_by' => null
                ],
                [
                    'equipment_id' => 15,
                    'equipment_number' => '2255-2234-060-10-1(3)/2-2(3)',
                    'equipment_name' => 'โต๊ะคอมพิวเตอร์ 1 ตัว บนาด 80x60x75 ซม.มีชั้นวางเคสด้านล่าง ชั้นวางแป้นพิมพ์ มีรูร้อยสายด้านบนและด้านหลัง',
                    'equipment_unit_price' => null,
                    'description' => 'ห้องปฏิบัติการ',
                    'user_id' => null,
                    'location_of_equipment' => null,
                    'equipment_unit' => 'ตัว',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'deleted_at' => null,
                    'created_by' => null,
                    'updated_by' => null,
                    'deleted_by' => null
                ],
                [
                    'equipment_id' => 16,
                    'equipment_number' => '2255-2234-060-10-1(3)/3-2(4)',
                    'equipment_name' => 'เครื่องคอมพิวเตอร์ Acer Veriton S4610G สเปคเดียวกันกับ Com # 3',
                    'equipment_unit_price' => null,
                    'description' => 'โอนให้ วิศวกรรมการผลิต',
                    'user_id' => null,
                    'location_of_equipment' => 'ห้องปฏิบัติการเชิงวิศวกรรมการผลิต',
                    'equipment_unit' => 'เครื่อง',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'deleted_at' => null,
                    'created_by' => null,
                    'updated_by' => null,
                    'deleted_by' => null
                ],
                [
                    'equipment_id' => 17,
                    'equipment_number' => '2255-2234-060-10-1(3)/4-1(4)',
                    'equipment_name' => 'เครื่องคอมพิวเตอร์ Acer Veriton S4610G สเปคเดียวกันกับ Com # 3',
                    'equipment_unit_price' => null,
                    'description' => 'ห้องปฏิบัติการเชิงวิศวกรรมการผลิต',
                    'user_id' => null,
                    'location_of_equipment' => 'ห้องปฏิบัติการเชิงวิศวกรรมการผลิต',
                    'equipment_unit' => 'เครื่อง',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'deleted_at' => null,
                    'created_by' => null,
                    'updated_by' => null,
                    'deleted_by' => null
                ],
                [
                    'equipment_id' => 18,
                    'equipment_number' => '2255-2234-060-10-1(3)/5-1(5)',
                    'equipment_name' => 'เครื่องคอมพิวเตอร์ Acer Veriton S4610G สเปคเดียวกันกับ Com # 3',
                    'equipment_unit_price' => null,
                    'description' => 'ห้องปฏิบัติการเชิงวิศวกรรมการผลิต',
                    'user_id' => null,
                    'location_of_equipment' => 'ห้องปฏิบัติการเชิงวิศวกรรมการผลิต',
                    'equipment_unit' => 'เครื่อง',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'deleted_at' => null,
                    'created_by' => null,
                    'updated_by' => null,
                    'deleted_by' => null
                ],
                [
                    'equipment_id' => 19,
                    'equipment_number' => '2255-2234-060-10-1(3)/6-1(6)',
                    'equipment_name' => 'เครื่องคอมพิวเตอร์ Acer Veriton S4610G สเปคเดียวกันกับ Com # 3',
                    'equipment_unit_price' => null,
                    'description' => 'ห้องปฏิบัติการเชิงวิศวกรรมการผลิต',
                    'user_id' => null,
                    'location_of_equipment' => 'ห้องปฏิบัติการเชิงวิศวกรรมการผลิต',
                    'equipment_unit' => 'เครื่อง',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'deleted_at' => null,
                    'created_by' => null,
                    'updated_by' => null,
                    'deleted_by' => null
                ],
                [
                    'equipment_id' => 20,
                    'equipment_number' => '2255-2234-060-10-1(3)/7-1(7)',
                    'equipment_name' => 'เครื่องคอมพิวเตอร์ Acer Veriton S4610G สเปคเดียวกันกับ Com # 3',
                    'equipment_unit_price' => null,
                    'description' => 'ห้องปฏิบัติการเชิงวิศวกรรมการผลิต',
                    'user_id' => null,
                    'location_of_equipment' => 'ห้องปฏิบัติการเชิงวิศวกรรมการผลิต',
                    'equipment_unit' => 'เครื่อง',
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                    'deleted_at' => null,
                    'created_by' => null,
                    'updated_by' => null,
                    'deleted_by' => null
                ]
            ]
        );
    }
}
